- name: Ensure the passed k8s_version is supported. If you think this is wrong, disable this check.
  shell: "curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-{{ arch }}/Packages | grep 'Package: kubelet' -A 2 | grep 'Version' | awk '{print $2}'"
  register: k8s_versions
  when: check_version_exists
  until: k8s_versions.stdout.find( k8s_version ) != -1
  changed_when: k8s_versions.rc == 1
  no_log: true
  delay: 1

- name: Remove swapfile from /etc/fstab
  mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
  with_items:
      - swap
      - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Load br_netfilter explicitly
  command: modprobe br_netfilter

- name: br_netfilter setup
  copy:
      dest: "{{ item.dest }}"
      content: "{{ item.content }}"
  with_items:
      - dest: /etc/modules-load.d/k8s.conf
        content: |
            br_netfilter

      - dest: /etc/sysctl.d/k8s.conf
        content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1

- name: Run sysctl
  command: |
      sysctl --system

- name: Add an apt signing key for Kubernetes
  apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
      keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Adding apt repository for Kubernetes
  apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
          - "kubelet={{ k8s_version }}"
          - "kubeadm={{ k8s_version }}"
          - "kubectl={{ k8s_version }}"
  notify: restart kubelet

- name: Hold K8S binaries
  dpkg_selections:
      name: "{{ item }}"
      selection: hold
  with_items:
      - kubelet
      - kubeadm
      - kubectl

